[package]
name = "proxy"
version = "0.1.0"
authors = ["mint"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web="1.0.8"
reqwest = "0.9.21"
getopts = "0.2.21"
